// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWEXMwtN6yY48UU-Bhqgzs3hGlcO3ihQg',
    appId: '1:26541640171:web:7469c4aca2620fb17271ae',
    messagingSenderId: '26541640171',
    projectId: 'aisobes',
    authDomain: 'aisobes.firebaseapp.com',
    storageBucket: 'aisobes.firebasestorage.app',
    measurementId: 'G-42QMX36069',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBxiyiwRkNj1WrhkrmqUe--bM1HGqpPc',
    appId: '1:26541640171:android:4331f4403e29a5b47271ae',
    messagingSenderId: '26541640171',
    projectId: 'aisobes',
    storageBucket: 'aisobes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrW38TdFOUDyNWbBRTc_3VBQpm30VxelQ',
    appId: '1:26541640171:ios:202c54144cfab97b7271ae',
    messagingSenderId: '26541640171',
    projectId: 'aisobes',
    storageBucket: 'aisobes.firebasestorage.app',
    iosBundleId: 'com.example.aisobes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrW38TdFOUDyNWbBRTc_3VBQpm30VxelQ',
    appId: '1:26541640171:ios:202c54144cfab97b7271ae',
    messagingSenderId: '26541640171',
    projectId: 'aisobes',
    storageBucket: 'aisobes.firebasestorage.app',
    iosBundleId: 'com.example.aisobes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWEXMwtN6yY48UU-Bhqgzs3hGlcO3ihQg',
    appId: '1:26541640171:web:f820b21ce6c5d8587271ae',
    messagingSenderId: '26541640171',
    projectId: 'aisobes',
    authDomain: 'aisobes.firebaseapp.com',
    storageBucket: 'aisobes.firebasestorage.app',
    measurementId: 'G-SV432XK5NT',
  );
}
